### ISSUE TITLE
getting Unix syslog delivery error when running docker image

### ISSUE THREAD

**Issue by sasimachi** [emmanuelvisage/docker-mongo-bi-connector#1]
Hi,

I am trying the similar approach to start mongosqld within a docker container but hitting with the following error like "Unix syslog delivery error".

Can you please let me know whether you hit this issue anytime.

-
sasi

**Comment by NicoThiebaut** [comment]
Hello Sasimachi,

What Docker base image are you using? Can you share your Dockerfile?

In order to see the logs you need to install rsyslog and start it (with `apt-get install rsyslog && service rsyslog start` if you use a debian-based base image). This way you'll be able to see the connector's logs and understand what's going on. 

Note that I have been able to solve a similar issue adding  `--logPath=/log/sqld.log` to the mongosqld call (see [this link](https://tutel.me/c/programming/questions/49389972/quotunix+syslog+delivery+errorquot+in+debian+docker+image)).

Nicolas

**Comment by sasimachi** [comment]
Hi Nicolas,

Followed similar approach and able to fix the issue.
Thanks for your help.

Sasikanth
